-- DevOps — Créer des objets (tables, procédures, file formats)

USE ROLE dev_sec_ops_role;

CREATE DATABASE IF NOT EXISTS  HEALT_APP_PROJET;
CREATE OR REPLACE WAREHOUSE my_wh WITH WAREHOUSE_SIZE='X-SMALL' INITIALLY_SUSPENDED=TRUE;


GRANT USAGE ON DATABASE HEALT_APP_PROJET TO ROLE dev_sec_ops_role;
GRANT CREATE SCHEMA ON DATABASE HEALT_APP_PROJET TO ROLE dev_sec_ops_role;
CREATE SCHEMA IF NOT EXISTS HEALT_APP_PROJET.RAW;
CREATE SCHEMA IF NOT EXISTS HEALT_APP_PROJET.COMMON;
CREATE SCHEMA IF NOT EXISTS HEALT_APP_PROJET.STAGING;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE dev_sec_ops_role;


-- Accès à la DB et aux schémas
GRANT USAGE ON DATABASE HEALT_APP_PROJET          TO ROLE dev_ops_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.RAW        TO ROLE dev_ops_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.STAGING    TO ROLE dev_ops_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.COMMON     TO ROLE dev_ops_role;

-- Droits DDL sur chaque schéma
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE FILE FORMAT, CREATE STREAM, CREATE SEQUENCE
    ON SCHEMA HEALT_APP_PROJET.RAW     TO ROLE dev_ops_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE FILE FORMAT, CREATE STREAM, CREATE SEQUENCE
    ON SCHEMA HEALT_APP_PROJET.STAGING TO ROLE dev_ops_role;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE FILE FORMAT, CREATE STREAM, CREATE SEQUENCE
    ON SCHEMA HEALT_APP_PROJET.COMMON  TO ROLE dev_ops_role;

GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE HEALT_APP_PROJET    TO ROLE dev_ops_role;
GRANT CREATE STAGE ON FUTURE SCHEMAS IN DATABASE HEALT_APP_PROJET TO ROLE dev_ops_role;

GRANT CREATE PIPE ON ALL SCHEMAS IN DATABASE HEALT_APP_PROJET    TO ROLE dev_ops_role;
GRANT CREATE PIPE ON FUTURE SCHEMAS IN DATABASE HEALT_APP_PROJET TO ROLE dev_ops_role;

-- Warehouse pour exécuter les DDL interactivement
GRANT USAGE ON WAREHOUSE MY_WH TO ROLE dev_ops_role;

-- Application — Créer et exécuter des tasks

-- Accès à la DB et aux schémas
GRANT USAGE ON DATABASE HEALT_APP_PROJET       TO ROLE app_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.RAW     TO ROLE app_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.STAGING TO ROLE app_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.COMMON  TO ROLE app_role;

-- Créer des tasks dans les schémas
GRANT CREATE TASK ON SCHEMA HEALT_APP_PROJET.RAW     TO ROLE app_role;
GRANT CREATE TASK ON SCHEMA HEALT_APP_PROJET.STAGING TO ROLE app_role;
GRANT CREATE TASK ON SCHEMA HEALT_APP_PROJET.COMMON TO ROLE app_role;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.COMMON  TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.RAW TO ROLE APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.COMMON  TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.RAW TO ROLE APP_ROLE;
-- GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE HEALT_APP_PROJET.COMMON.DATA_TO_PROCESS TO ROLE APP_ROLE;

GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE APP_ROLE;

-- Warehouse pour exécuter les tasks
GRANT USAGE ON WAREHOUSE MY_WH TO ROLE app_role;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE APP_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE APP_ROLE;

GRANT USAGE  ON DATABASE HEALT_APP_PROJET       TO ROLE APP_ROLE;
GRANT USAGE  ON SCHEMA HEALT_APP_PROJET.COMMON  TO ROLE APP_ROLE;
GRANT CREATE STREAM ON SCHEMA HEALT_APP_PROJET.COMMON TO ROLE APP_ROLE;

-- Droits sur la table source dans RAW
GRANT USAGE  ON SCHEMA HEALT_APP_PROJET.RAW     TO ROLE APP_ROLE;
--GRANT SELECT ON TABLE HEALT_APP_PROJET.RAW.RAW_EVENTS TO ROLE APP_ROLE;


GRANT OPERATE ON ALL TASKS IN SCHEMA HEALT_APP_PROJET.RAW     TO ROLE app_role;
GRANT OPERATE ON ALL TASKS IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE app_role;
GRANT OPERATE ON ALL TASKS IN SCHEMA HEALT_APP_PROJET.COMMON TO ROLE app_role;

-- Tasks futures
GRANT OPERATE ON FUTURE TASKS IN SCHEMA HEALT_APP_PROJET.RAW     TO ROLE app_role;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE app_role;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA HEALT_APP_PROJET.COMMON TO ROLE app_role;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE APP_ROLE;


-- Droits sur les schemas
GRANT USAGE ON DATABASE HEALT_APP_PROJET          TO ROLE APP_ROLE;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.RAW        TO ROLE APP_ROLE;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.COMMON     TO ROLE APP_ROLE;

-- Droits sur les tables
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.RAW    TO ROLE APP_ROLE;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.COMMON TO ROLE APP_ROLE;

-- Droits sur les streams
GRANT SELECT ON ALL STREAMS IN SCHEMA HEALT_APP_PROJET.RAW    TO ROLE APP_ROLE;
GRANT SELECT ON ALL STREAMS IN SCHEMA HEALT_APP_PROJET.COMMON TO ROLE APP_ROLE;

-- Droits sur les procédures
GRANT USAGE ON ALL PROCEDURES IN SCHEMA HEALT_APP_PROJET.COMMON TO ROLE APP_ROLE;

-- Droits task + warehouse
GRANT EXECUTE TASK         ON ACCOUNT              TO ROLE APP_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT              TO ROLE APP_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH                TO ROLE APP_ROLE;

-- Pour les futurs objets créés par DEV_OPS_ROLE
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.RAW    TO ROLE APP_ROLE;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.COMMON TO ROLE APP_ROLE;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA HEALT_APP_PROJET.COMMON        TO ROLE APP_ROLE;
GRANT USAGE  ON FUTURE PROCEDURES IN SCHEMA HEALT_APP_PROJET.COMMON     TO ROLE APP_ROLE;

GRANT USAGE  ON ALL PROCEDURES IN SCHEMA HEALT_APP_PROJET.COMMON     TO ROLE APP_ROLE;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE APP_ROLE;

-- Droits sur les futures tables
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE APP_ROLE;

GRANT USAGE ON ALL FUNCTIONS IN SCHEMA HEALT_APP_PROJET.COMMON TO ROLE APP_ROLE;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA HEALT_APP_PROJET.RAW    TO ROLE APP_ROLE;

-- Et pour les futures fonctions créées par DEV_OPS_ROLE
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA HEALT_APP_PROJET.COMMON TO ROLE APP_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA HEALT_APP_PROJET.RAW    TO ROLE APP_ROLE;


-- -- Engineer — Lire les données + monitorer les tasks

-- Accès à la DB et aux schémas
GRANT USAGE ON DATABASE HEALT_APP_PROJET       TO ROLE engineer_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.RAW     TO ROLE engineer_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.STAGING TO ROLE engineer_role;
GRANT USAGE ON SCHEMA HEALT_APP_PROJET.COMMON  TO ROLE engineer_role;

-- Lecture des tables et vues existantes
GRANT SELECT ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.RAW     TO ROLE engineer_role;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE engineer_role;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALT_APP_PROJET.COMMON  TO ROLE engineer_role;
GRANT SELECT ON ALL VIEWS  IN SCHEMA HEALT_APP_PROJET.RAW     TO ROLE engineer_role;
GRANT SELECT ON ALL VIEWS  IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE engineer_role;

-- Tables et vues futures (automatiquement accordées)
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.RAW     TO ROLE engineer_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE engineer_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALT_APP_PROJET.COMMON  TO ROLE engineer_role;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA HEALT_APP_PROJET.RAW     TO ROLE engineer_role;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE engineer_role;

-- Monitorer les tasks (MONITOR = voir le statut/historique)
GRANT MONITOR ON ALL TASKS IN SCHEMA HEALT_APP_PROJET.RAW     TO ROLE engineer_role;
GRANT MONITOR ON ALL TASKS IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE engineer_role;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA HEALT_APP_PROJET.RAW     TO ROLE engineer_role;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA HEALT_APP_PROJET.STAGING TO ROLE engineer_role;

-- Warehouse pour les requêtes SELECT
GRANT USAGE ON WAREHOUSE MY_WH TO ROLE engineer_role;
